src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
#[ORM\Entity(repositoryClass: IngredientRepository::class)]
#[UniqueEntity('nom')]
class Ingredient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id ;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2, max:50)]
    private ?string $nom ;

    #[ORM\Column]
    #[Assert\Positive()]
    #[Assert\NotNull()]
    #[Assert\LessThan(200)]
    private ?float $Price ;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt ;

    #[ORM\ManyToOne(inversedBy: 'ingredients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;
public function __construct(){
    $this->createdAt = new \DateTimeImmutable();
}
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom; // You can customize this to return any string representation you want
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/IngredientType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
class IngredientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('nom', TextType::class, [
            'attr' => ['class' => 'form-control'],
            'label' => 'nom',
            'label_attr' => [
                'class' => 'form-label mt-4'
            ],
            'constraints' => [
                new Assert\Length(['min' => 2, 'max' => 50]),
                new Assert\NotBlank()
            ]
        ])
        
        ->add('Price', MoneyType::class, [
            'attr' => ['class' => 'form-control'],
            'label' => 'prix',
            'label_attr' => [
                'class' => 'form-label mt-4'
            ],
            'constraints' => [
                new Assert\Positive(),
                new Assert\LessThan(200)
            ]
        ])
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'btn btn-primary mt-4'],
                'label' => 'Créer mon ingrédient',
            ])
            
          ;  
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ingredient::class,
        ]);
    }
}

templates/pages/ingredient/edit.html.twig
{% extends 'base.html.twig' %}
  {% block body %}
  <div class="container">
<h1 class="mt-4">modification d'un ingredient</h1>

{{ form_start(form) }}
 
<div class="form-group">
{{ form_label(form.nom) }}
   {{ form_widget(form.nom)}}
 <div class="form-error">
        {{ form_errors(form.nom) }}
    </div>
</div> 
<div class="form-group">
{{ form_label(form.Price) }}
   {{ form_widget(form.Price) }}
 <div class="form-error">
        {{ form_errors(form.Price) }}
    </div>
</div>

<div class="form-group">
 {{ form_row(form.submit) }}
</div>

{{ form_end(form) }}
  </div>

  {% endblock %}

templates/pages/ingredient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}symRecipe mes ingredients{% endblock %}

{% block body %}

  

 {% for message in app.flashes('success') %}
    <div class=" alert alert-success">
        {{ message }}
    </div>
{% endfor %}
<div class="container mt-4">
<h1>mes ingredients</h1>
<div class="count">
  <p> il ya{{ ingredients.getTotalItemCount }} ingredient au total</p>
</div>

 <a href="{{path('ingredient.new')}}" class="btn btn-primary">Ajouter ingredient</a>
</hr>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Numero</th>
      <th scope="col">Nom</th>
      <th scope="col">Prix</th>
      <th scope="col">createdAt</th>
         <th scope="col">delet</th>
         <th scope="col">edit</th>
    </tr>
  </thead>
  <tbody>
    {% for ingredient in ingredients %}
   <tr class="table-primary">
      <th scope="row">{{ingredient.id}}</th>
      <td>{{ingredient.nom}}</td>
      <td>{{ingredient.price}}</td>
      <td>{{ingredient.createdAt|date("m/d/Y")}}</td>
      
      <td><a href="{{ path('ingredient.delet', {'id':ingredient.id})}}"  class="btn btn-danger">supprimer</a></td>
 <td><a href="{{ path('ingredient.edit', {'id':ingredient.id})}}" style="color: yellow;" class="btn btn-primary">Edit</a></td>

      

    </tr>
{% endfor %}
   
   
  </tbody>
</table>
<div class="d-flex justify-content-center">
    {{ knp_pagination_render(ingredients) }}
</div>
</div>

{% endblock %}

templates/pages/ingredient/new.html.twig
{% extends 'base.html.twig' %}
  {% block body %}
  <div class="container">
<h1 class="mt-4">creation d'un ingredient</h1>

{{ form_start(form) }}
 
<div class="form-group">
{{ form_label(form.nom) }}
   {{ form_widget(form.nom)}}
 <div class="form-error">
        {{ form_errors(form.nom) }}
    </div>
</div> 
<div class="form-group">
{{ form_label(form.Price) }}
   {{ form_widget(form.Price) }}
 <div class="form-error">
        {{ form_errors(form.Price) }}
    </div>
</div>

<div class="form-group">
 {{ form_row(form.submit) }}
</div>

{{ form_end(form) }}
  </div>

  {% endblock %}